### ISSUE TITLE
vte 0.44

### ISSUE THREAD

**Issue by ten0r** [linvinus/AltYo#53]
Altyo can't be build with vte 0.44.*
`/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libvte-2.91.so: undefined reference to 'gtk_widget_class_set_css_name'`

**Comment by ten0r** [comment]
Sorry. 
It can't be compiled with vte 0.44 and without gtk3.20.
